import {category} from "./category.js";
import {itemHover} from "./item-hover.js";
import {mainSlide} from "./main-slide.js";
import {modalMap} from "./modal-map.js";
import {servicesAdditional} from "./services-additional.js";
import {write} from "./write.js";
import {range} from "./range.js";
category();
itemHover();
mainSlide();
modalMap();
servicesAdditional();
write();
range();
